{"UniqueId":"d5d32ea2-b832-4700-ac5b-721007d978ff","AppType":1,"DateTime":"3/31/2020 8:41:09 PM","Namespace":"ReshimgathiServices.Controllers.LoginController","Controller":"Login","IsExceptionHandled":null,"Exception":"Manual exception thrown.","ErrorCode":"-2146233088","FileName":"C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs","MethodName":"VerifyLoginDetails","LineNo":26,"ColumnNo":13,"StackTrace":"   at ReshimgathiServices.Controllers.LoginController.VerifyLoginDetails(LoginRequest req) in C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs:line 26\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()","Host":"localhost","Version":"1.1"}
{"UniqueId":"349e7c34-4a45-4627-bb19-ca83325e193b","AppType":1,"DateTime":"3/31/2020 8:41:09 PM","Namespace":"ReshimgathiServices.Controllers.LoginController","Controller":"Login","IsExceptionHandled":null,"Exception":"Manual exception thrown.","ErrorCode":"-2146233088","FileName":"C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs","MethodName":"VerifyLoginDetails","LineNo":26,"ColumnNo":13,"StackTrace":"   at ReshimgathiServices.Controllers.LoginController.VerifyLoginDetails(LoginRequest req) in C:\\E\\VS-Programs\\Organizations\\Reshimgathi\\ReshimgathiServices\\ReshimgathiServices\\ReshimgathiServices\\Controllers\\LoginController.cs:line 26\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()","Host":"localhost","Version":"1.1"}
